import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export async function generatePdfBuffer(prediction, farmNameOverride = null) {
  const pdfDoc = await PDFDocument.create();
  
  // Embed standard fonts
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // Theme Colors (Warm White Theme)
  const bgColor = rgb(250/255, 248/255, 245/255); // #faf8f5
  const primaryColor = rgb(16/255, 185/255, 129/255); // #10b981
  const textDark = rgb(31/255, 41/255, 55/255); // #1f2937
  const textMuted = rgb(75/255, 85/255, 99/255); // #4b5563

  let page;
  let width, height;
  let y;

  const addNewPage = () => {
    page = pdfDoc.addPage([595, 842]); // A4 Size
    width = page.getSize().width;
    height = page.getSize().height;
    page.drawRectangle({ x: 0, y: 0, width, height, color: bgColor });
    y = height - 50;
  };

  addNewPage();

  const checkPageBreak = (spaceNeeded) => {
    if (y - spaceNeeded < 50) {
      addNewPage();
    }
  };

  const writeText = (text, size, textFont, color, align = 'left') => {
    if (!text) return;
    // Replace Rupee symbol with 'Rs.' to prevent WinAnsi encoding errors in standard fonts
    const sanitizedText = String(text).replace(/₹/g, 'Rs.');
    const lines = sanitizedText.split('\n');
    for (const line of lines) {
      const words = line.split(' ');
      let currentLine = '';
      for (const word of words) {
        const testLine = currentLine + word + ' ';
        const textWidth = textFont.widthOfTextAtSize(testLine, size);
        
        if (textWidth > width - 100) {
          checkPageBreak(size * 1.5);
          const xPos = align === 'center' ? (width - textFont.widthOfTextAtSize(currentLine.trim(), size)) / 2 : 50;
          page.drawText(currentLine.trim(), { x: xPos, y, size, font: textFont, color });
          y -= size * 1.5;
          currentLine = word + ' ';
        } else {
          currentLine = testLine;
        }
      }
      if (currentLine.trim()) {
        checkPageBreak(size * 1.5);
        const xPos = align === 'center' ? (width - textFont.widthOfTextAtSize(currentLine.trim(), size)) / 2 : 50;
        page.drawText(currentLine.trim(), { x: xPos, y, size, font: textFont, color });
        y -= size * 1.5;
      }
    }
  };

  const addSection = (title, content) => {
    if (!content || content.trim() === '') return;
    checkPageBreak(40);
    y -= 10;
    writeText(title, 14, boldFont, primaryColor);
    y -= 5;
    writeText(content, 10, font, textDark);
    y -= 15;
  };

  // Title
  writeText('Agrovision AI', 24, boldFont, primaryColor, 'center');
  y -= 5;
  writeText('Agronomic Analysis Report', 16, boldFont, textMuted, 'center');
  y -= 20;

  // Farm Details
  let farmName = farmNameOverride || 'Unknown Farm';
  if (!farmNameOverride && prediction.farms) {
    if (Array.isArray(prediction.farms) && prediction.farms.length > 0) farmName = prediction.farms[0].name;
    else if (!Array.isArray(prediction.farms)) farmName = prediction.farms.name;
  }

  addSection('Farm Profile', `Farm Name: ${farmName}\nLocation: ${prediction.village || 'N/A'}, ${prediction.district || 'N/A'}, ${prediction.state || 'N/A'}`);
  addSection('AI Recommendation', `Recommended Crop: ${String(prediction.crop || 'Unknown').toUpperCase()}\nConfidence Score: ${prediction.confidence || 0}%\nExpected Yield: ${prediction.expected_yield || 'N/A'}\nExpected Profit: ${prediction.expected_profit || 'N/A'}`);
  addSection('Health Diagnostics', `Farm Health Score: ${prediction.farm_health_score || 0}/100\nSoil Health Score: ${prediction.soil_health_score || 0}/100`);

  if (prediction.weather_data) {
    addSection('Environmental Baselines', `Temperature: ${prediction.weather_data.temperature || 'N/A'} C\nRainfall (Monthly Avg): ${prediction.weather_data.rainfall || 'N/A'} mm\nSoil Nitrogen: ${prediction.nitrogen || 'N/A'} g/kg\nSoil pH: ${prediction.ph || 'N/A'}`);
  }

  // Detailed JSON Insights
  addSection('Expert Insights', prediction.explanation);
  addSection('Soil Analysis', prediction.soil_analysis);
  addSection('Fertilizer Plan', prediction.fertilizer_plan);
  addSection('Irrigation Schedule', prediction.irrigation_schedule);

  // Footer
  checkPageBreak(30);
  y -= 20;
  writeText('Report auto-generated by Agrovision AI Platform.', 8, font, textMuted, 'center');

  // Return the PDF buffer directly
  return await pdfDoc.save();
}
