import urllib.request
import urllib.parse
import json
import concurrent.futures
import time

en = {
  'brand': 'AgroMind AI',
  'tagline': 'AI-Powered Smart Farming Intelligence Platform',
  'dashboard': 'Dashboard',
  'predict': 'Predict Crop',
  'disease': 'Disease Scanner',
  'advisor': 'AI Advisor',
  'logout': 'Logout',
  'login': 'Login',
  'register': 'Register',
  'total_predictions': 'Total Predictions',
  'active_farms': 'Active Farms',
  'average_ph': 'Average pH',
  'weather_score': 'Weather Score',
  'farm_score': 'Farm Health Score',
  'recommended_crops': 'Recommended Crops',
  'yield_projections': 'Yield Forecast',
  'profit_forecast': 'Profit Forecast',
  'disease_alerts': 'Disease Alerts',
  'run_predictor': 'Analyze Farm',
  'leaf_scan': 'Scan Leaf',
  'nitrogen': 'Nitrogen',
  'phosphorus': 'Phosphorus',
  'potassium': 'Potassium',
  'ph': 'Soil pH',
  'state': 'State',
  'district': 'District',
  'season': 'Sowing Season',
  'calculate': 'Execute AI Recommendation',
  'chatbot': 'AI Chatbot',
  'q1': 'Which crop should I grow?',
  'q2': 'How much fertilizer do I need?',
  'q3': 'Will rain affect my crop?',
  'q4': 'How can I increase yield?',
  'q5': 'How can I prevent disease?',
  'chatbot_placeholder': 'Ask me anything about farming...',
  'landing_hero_badge': 'Precision Agriculture Platform — Powered by Gemini AI',
  'landing_hero_title1': 'Smart Farming',
  'landing_hero_title2': 'Intelligence',
  'landing_hero_desc': 'Upload farm photographs, allow GPS access, and let AgroMind AI automatically analyze soil, weather, and crop conditions — no manual data entry required.',
  'landing_hero_btn1': 'Analyze My Farm',
  'landing_hero_btn2': 'Create Free Account',
  'landing_hero_latest_title': 'Latest AI Analysis',
  'landing_hero_rice_match': 'Rice — 94.2% Match',
  'landing_hero_kharif_maha': 'Kharif Season · Maharashtra',
  'landing_hero_farm_health': 'Farm Health',
  'landing_hero_soil_health': 'Soil Health',
  'landing_hero_confidence': 'Confidence',
  'landing_hero_yield_est': 'Yield Est.',
  'landing_hero_soilgrids_badge': '✅ SoilGrids Auto-fetched',
  'landing_how_title': 'Zero Manual Data Entry',
  'landing_how_desc': 'All soil, weather, and location parameters are fetched automatically from trusted scientific APIs.',
  'landing_step1_title': 'Upload Farm Photos',
  'landing_step1_desc': 'Upload images of your farm, soil, or crops (JPG, PNG, WEBP).',
  'landing_step2_title': 'Allow Location Access',
  'landing_step2_desc': 'Grant GPS access — coordinates fetch real-time weather & soil data.',
  'landing_step3_title': 'AI Analyzes Everything',
  'landing_step3_desc': 'Gemini Vision + SoilGrids + Open-Meteo compile a full agronomic report.',
  'landing_step4_title': 'Get Your Farm Report',
  'landing_step4_desc': 'Receive crop recommendations, fertilizer plan & downloadable PDF.',
  'landing_features_title': 'Everything a Modern Farmer Needs',
  'landing_features_desc': 'From real-time soil analysis to multilingual voice advice — all in one platform.',
  'landing_feat1_title': 'AI Crop Prediction',
  'landing_feat1_desc': 'Upload farm images and grant GPS access. AI automatically pulls SoilGrids soil data, Open-Meteo weather forecasts, and recommends the best crops for your land.',
  'landing_feat2_title': 'Leaf Disease Scanner',
  'landing_feat2_desc': 'Photograph any diseased crop leaf. Gemini Vision AI identifies rusts, blights, fungal spots, and nutrient deficiencies within seconds.',
  'landing_feat3_title': 'Voice AI Advisor',
  'landing_feat3_desc': 'Speak directly to your farm advisor in English, Hindi, or Marathi. Get personalized agronomy advice with multilingual voice input and output.',
  'landing_try_now': 'Try it now →',
  'landing_cta_title': 'Start Optimizing Your Farm Today',
  'landing_cta_desc': 'No hardware, no manual data entry — just your phone. GPS + photos → instant agronomic recommendations.',
  'landing_cta_btn1': 'Create Free Account',
  'landing_cta_btn2': 'Analyze Farm Now',
  'dash_loading': 'Loading your Agronomy Dashboard...',
  'dash_admin_title': 'Admin Console',
  'dash_admin_desc': 'Monitor precision systems and check agricultural AI metrics.',
  'dash_admin_active_farmers': 'Active Farmers',
  'dash_admin_total_preds': 'Total Predictions',
  'dash_admin_path_scans': 'Pathology Scans',
  'dash_admin_ai_accuracy': 'AI System Accuracy',
  'dash_farmer_title': 'Farmer Workspace',
  'dash_farmer_desc': 'View real-time farm health indices, soil parameters, and climate metrics.',
  'dash_btn_analyze': 'Analyze Farm',
  'dash_btn_scan': 'Scan Leaf',
  'dash_metric_farm_health': 'Farm Health Score',
  'dash_metric_soil_health': 'Soil Health Score',
  'dash_metric_weather': 'Weather Condition',
  'dash_metric_disease': 'Disease Alerts',
  'dash_latest_badge': 'Latest Analysis',
  'dash_latest_title': 'Recommended Crop:',
  'dash_latest_yield': 'Expected Yield',
  'dash_latest_revenue': 'Expected Revenue',
  'dash_latest_profit': 'Expected Profit',
  'predict_title': 'Analyze My Farm',
  'predict_desc': 'Upload images and allow location access to automatically compile soil, weather, and AI recommendations.',
  'predict_step1': 'Upload Snapshots',
  'predict_step2': 'Location & Run',
  'predict_step3': 'AI Compilation',
  'predict_step4': 'Agronomic Report',
  'predict_s1_title': 'Farm & Crop Images',
  'predict_s1_desc': 'Upload farm snapshots, soil images, or leaf photographs. Supported formats: JPG, PNG, WEBP.',
  'predict_s1_drag': 'Drag & Drop or Select Images',
  'predict_s1_btn': 'Continue to Location',
  'predict_s2_farm_name': 'Farm Name',
  'predict_s2_title': 'Location Data',
  'predict_s2_desc1': 'We have your saved farm location. You can proceed with analysis, or update it if you have moved.',
  'predict_s2_coords': 'Coordinates: Lat',
  'predict_s2_btn_updating': 'Updating...',
  'predict_s2_btn_update': 'Update Location',
  'predict_s2_desc2': 'Grant browser location access to automatically pull meteorological data from Open-Meteo and chemical parameters from SoilGrids.',
  'predict_s2_btn_loading': 'Loading...',
  'predict_s2_btn_allow': 'Allow Location Access',
  'predict_s2_btn_back': 'Back',
  'predict_s2_btn_execute': 'Execute Automated Analysis',
  'predict_s3_title': 'AgroMind AI Engine Processing...',
  'predict_s4_geo': 'Geocoded Location',
  'predict_s4_btn_dl_loading': 'Downloading...',
  'predict_s4_btn_dl': 'Download PDF Report',
  'predict_s4_farm_h': 'Farm Health Score',
  'predict_s4_farm_h_desc': 'Vegetative growth, hydration density, and crop condition parameters.',
  'predict_s4_soil_h': 'Soil Health Score',
  'predict_s4_soil_h_desc': 'Estimated organic carbon, mineral nutrient balance.',
  'predict_s4_main_crop': 'Main Crop Recommendation',
  'predict_s4_conf': 'Confidence',
  'predict_s4_duration': 'Duration',
  'predict_s4_yield': 'Yield',
  'predict_s4_profit': 'Profit',
  'disease_title': 'Crop Leaf Pathology Scanner',
  'disease_desc': 'Upload a photo of a diseased leaf to instantly identify crop issues and receive AI-driven treatment recommendations.',
  'disease_upload_title': 'Image Upload',
  'disease_upload_desc': 'Select the crop type and upload a clear leaf photograph.',
  'disease_crop_type': 'Crop Type',
  'disease_crop_tomato': 'Tomato',
  'disease_crop_potato': 'Potato',
  'disease_crop_cotton': 'Cotton',
  'disease_crop_wheat': 'Wheat',
  'disease_crop_rice': 'Rice',
  'disease_crop_sugarcane': 'Sugarcane',
  'disease_crop_other': 'Other',
  'disease_drag': 'Drag & Drop Leaf Image',
  'disease_btn_scan': 'Scan Leaf Pathology',
  'disease_btn_scanning': 'Scanning leaf vectors...',
  'disease_report_title': 'Pathology Diagnostic Report',
  'disease_match_conf': 'Match Confidence',
  'disease_treatment': 'Treatment Plan',
  'disease_medicine': 'Recommended Medicine',
  'disease_prevention': 'Prevention Strategy',
  'disease_recovery': 'Est. Recovery Time',
  'advisor_title': 'AI Chatbot',
  'advisor_desc': 'Ask agronomic queries in English, Hindi, or Marathi.',
  'advisor_btn_stop': 'Stop',
  'advisor_btn_voice_on': 'Voice ON',
  'advisor_btn_voice_off': 'Voice OFF',
  'advisor_welcome': 'Welcome to AgroMind Advisor',
  'advisor_welcome_desc': 'How can I help you today? You can select a quick question below, write your query, or click the microphone to speak.',
  'advisor_btn_speak': 'Speak',
  'advisor_thinking': 'Advisor is thinking...',
  'advisor_listening': 'Listening...',
  'advisor_placeholder': 'Ask me anything about farming...',
  'navbar_farmer': 'Farmer',
  'disease_healthy': 'Healthy',
  'disease_critical': 'Critical',
  'disease_high': 'High',
  'disease_medium': 'Medium',
  'disease_low': 'Low',
  'stable': 'Stable'
}

def translate(item):
    k, v, tl = item
    url = f'https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl={tl}&dt=t&q={urllib.parse.quote(v)}'
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    try:
        with urllib.request.urlopen(req) as res:
            data = json.loads(res.read().decode())
            return k, ''.join([part[0] for part in data[0]]), tl
    except Exception as e:
        return k, v, tl

tasks = []
for tl in ['kn', 'te', 'gu']:
    for k, v in en.items():
        tasks.append((k, v, tl))

results = {'kn': {}, 'te': {}, 'gu': {}}
with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
    for k, trans, tl in executor.map(translate, tasks):
        results[tl][k] = trans

with open('translations_kn_te_gu.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print('Done')
