import { NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { supabaseAdmin } from '../../../../../lib/supabase';

export async function GET(request, { params }) {
  const { id } = params;

  try {
    const { data: prediction, error } = await supabaseAdmin
      .from('predictions')
      .select('*, farms(*)')
      .eq('id', id)
      .single();

    if (error || !prediction) {
      return NextResponse.json({ message: "Report not found" }, { status: 404 });
    }

    // Generate the PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    // Collect data chunks
    doc.on('data', buffers.push.bind(buffers));

    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(
          new Response(pdfData, {
            status: 200,
            headers: {
              'Content-Type': 'application/pdf',
              'Content-Disposition': `inline; filename="AgroMind_Report_${id}.pdf"`,
            },
          })
        );
      });

      doc.on('error', (err) => {
        reject(err);
      });

      try {
        // PDF Content
        doc.fontSize(24).fillColor('#10b981').text('AgroMind AI', { align: 'center' });
        doc.fontSize(16).fillColor('#333333').text('Agronomic Analysis Report', { align: 'center' });
        doc.moveDown(2);

        // Farm Details
        let farmName = 'Unknown Farm';
        if (prediction.farms) {
          if (Array.isArray(prediction.farms) && prediction.farms.length > 0) farmName = prediction.farms[0].name;
          else if (!Array.isArray(prediction.farms)) farmName = prediction.farms.name;
        }
        
        doc.fontSize(14).fillColor('#10b981').text('Farm Profile');
        doc.fontSize(10).fillColor('#000000');
        doc.text(`Farm Name: ${farmName || 'Unknown Farm'}`);
        doc.text(`Location: ${prediction.village || 'N/A'}, ${prediction.district || 'N/A'}, ${prediction.state || 'N/A'}`);
        doc.moveDown(1);

        // AI Recommendation
        doc.fontSize(14).fillColor('#10b981').text('AI Recommendation');
        doc.fontSize(10).fillColor('#000000');
        doc.text(`Recommended Crop: ${String(prediction.crop || 'Unknown').toUpperCase()}`);
        doc.text(`Confidence Score: ${prediction.confidence || 0}%`);
        doc.text(`Expected Yield: ${prediction.expected_yield || 'N/A'}`);
        doc.text(`Expected Profit: ${prediction.expected_profit || 'N/A'}`);
        doc.moveDown(1);

        // Health Scores
        doc.fontSize(14).fillColor('#10b981').text('Health Diagnostics');
        doc.fontSize(10).fillColor('#000000');
        doc.text(`Farm Health Score: ${prediction.farm_health_score || 0}/100`);
        doc.text(`Soil Health Score: ${prediction.soil_health_score || 0}/100`);
        doc.moveDown(1);

        // Environmental Data
        if (prediction.weather_data) {
          doc.fontSize(14).fillColor('#10b981').text('Environmental Baselines');
          doc.fontSize(10).fillColor('#000000');
          doc.text(`Temperature: ${prediction.weather_data.temperature || 'N/A'}°C`);
          doc.text(`Rainfall (Monthly Avg): ${prediction.weather_data.rainfall || 'N/A'} mm`);
          doc.text(`Soil Nitrogen: ${prediction.nitrogen || 'N/A'} g/kg`);
          doc.text(`Soil pH: ${prediction.ph || 'N/A'}`);
          doc.moveDown(1);
        }

        // Expert Explanation
        doc.fontSize(14).fillColor('#10b981').text('Expert Insights');
        doc.fontSize(10).fillColor('#333333');
        doc.text(String(prediction.explanation || 'No detailed insights available.'), { align: 'justify', lineGap: 2 });
        
        doc.moveDown(3);
        doc.fontSize(8).fillColor('#888888').text('Report auto-generated by AgroMind AI Platform.', { align: 'center' });

        doc.end();
      } catch (docErr) {
        reject(docErr);
      }
    });
  } catch (err) {
    console.error("PDF generation failed:", err);
    return NextResponse.json({ message: "Internal server error during PDF generation", error: String(err.message), stack: String(err.stack) }, { status: 500 });
  }
}
