import { NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { supabaseAdmin } from '../../../../../../lib/supabase';

export async function GET(request, { params }) {
  const { id } = params;

  try {
    const { data: prediction, error } = await supabaseAdmin
      .from('predictions')
      .select('*, farms(*)')
      .eq('id', id)
      .single();

    if (error || !prediction) {
      return NextResponse.json({ message: "Report not found" }, { status: 404 });
    }

    // Generate the PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    // Collect data chunks
    doc.on('data', buffers.push.bind(buffers));

    return new Promise((resolve) => {
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(
          new NextResponse(pdfData, {
            status: 200,
            headers: {
              'Content-Type': 'application/pdf',
              'Content-Disposition': `inline; filename="AgroMind_Report_${id}.pdf"`,
            },
          })
        );
      });

      // PDF Content
      doc.fontSize(24).fillColor('#10b981').text('AgroMind AI', { align: 'center' });
      doc.fontSize(16).fillColor('#333333').text('Agronomic Analysis Report', { align: 'center' });
      doc.moveDown(2);

      // Farm Details
      doc.fontSize(14).fillColor('#10b981').text('Farm Profile');
      doc.fontSize(10).fillColor('#000000');
      doc.text(`Farm Name: ${prediction.farms?.name || 'Unknown Farm'}`);
      doc.text(`Location: ${prediction.village}, ${prediction.district}, ${prediction.state}`);
      doc.moveDown(1);

      // AI Recommendation
      doc.fontSize(14).fillColor('#10b981').text('AI Recommendation');
      doc.fontSize(10).fillColor('#000000');
      doc.text(`Recommended Crop: ${prediction.crop.toUpperCase()}`);
      doc.text(`Confidence Score: ${prediction.confidence}%`);
      doc.text(`Expected Yield: ${prediction.expected_yield}`);
      doc.text(`Expected Profit: ${prediction.expected_profit}`);
      doc.moveDown(1);

      // Health Scores
      doc.fontSize(14).fillColor('#10b981').text('Health Diagnostics');
      doc.fontSize(10).fillColor('#000000');
      doc.text(`Farm Health Score: ${prediction.farm_health_score}/100`);
      doc.text(`Soil Health Score: ${prediction.soil_health_score}/100`);
      doc.moveDown(1);

      // Environmental Data
      if (prediction.weather_data) {
        doc.fontSize(14).fillColor('#10b981').text('Environmental Baselines');
        doc.fontSize(10).fillColor('#000000');
        doc.text(`Temperature: ${prediction.weather_data.temperature}°C`);
        doc.text(`Rainfall (Monthly Avg): ${prediction.weather_data.rainfall} mm`);
        doc.text(`Soil Nitrogen: ${prediction.nitrogen} g/kg`);
        doc.text(`Soil pH: ${prediction.ph}`);
        doc.moveDown(1);
      }

      // Expert Explanation
      doc.fontSize(14).fillColor('#10b981').text('Expert Insights');
      doc.fontSize(10).fillColor('#333333');
      doc.text(prediction.explanation, { align: 'justify', lineGap: 2 });
      
      doc.moveDown(3);
      doc.fontSize(8).fillColor('#888888').text('Report auto-generated by AgroMind AI Platform.', { align: 'center' });

      doc.end();
    });
  } catch (err) {
    console.error("PDF generation failed:", err);
    return NextResponse.json({ message: "Internal server error during PDF generation" }, { status: 500 });
  }
}
